version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop_hub_db
    ports:
      - "5432:5432"
  web:
    build: .
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/shop_hub_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"